/* This code and any associated documentation is provided "as is"

Copyright 2024 Munich Quantum Software Stack Project

    Licensed under the Apache License, Version 2.0 with LLVM Exceptions (the
                                     "License"); you may not use this file
except in compliance with the License. You may obtain a copy of the License at

https://github.com/Munich-Quantum-Software-Stack/passes/blob/develop/LICENSE

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License.

SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
*************************************************************************
  author Martin Letras
  date   February 2025
  version 1.0
*************************************************************************/
/** @file
 * @brief
 * @details Header file that defines the signature for each MLIR/Quake defined
 * into the Munich Quantum Software Stack (MQSS).
 *
 * @par
 * This header must be included to use the collection of transforms passes that
 * are part of the MQSS.
 */

#pragma once

#include "mlir/Pass/Pass.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Pass/PassRegistry.h"

#include "llvm/Support/raw_ostream.h"

#include <stdexcept>
// #include "qdmi.h"
#include "sc/heuristic/HeuristicMapper.hpp"

/**
 * @def CUDAQ_PREFIX_FUNCTION
 * @brief Macro defining the prefix of each quantum kernel generated by
 * MLIR/Quake. This macro is used to identify MLIR/Quake quantum kernels.
 */
#define CUDAQ_PREFIX_FUNCTION "__nvqpp__mlirgen__"

namespace mqss::opt {

/**
 * @brief MLIR/Quake pass to perform the mapping of quantum circuits to
 superconducting devices using the MQT-QMAP.
   @details This method constructs an `mlir::Pass` of the type QuakeQMapPass.
 This pass operates on any MLIR/Quake module and performs the mapping of any
 given quantum circuit to an specific quantum superconducting device.
  @param[out] architecture is the selected superconducting quantum device
 configuration, including important information for mapping, i.e., connectivity
 of all the qubits
  @param[out] settings defines the configuration of the mapper, for more details
 visit MQT-QMAP official documentation.

  For example, given the following connectivity graph describing the relation of
 qubits in quantum arquictecture:

  \image html docs/_static/mqss-passes/connectivity_graph.png width=45%

  The MQT-QMAP tool re-maps the following two input circuits as follows:

  \image html docs/_static/mqss-passes/QuakeQMapPass-01.png width=50%
  \image html docs/_static/mqss-passes/QuakeQMapPass-02.png width=95%

 @return An `mlir::Pass` object containing the definition of the QuakeQMapPass.
 This `mlir::Pass` object has to be passed to an `mlir::PassManager` to take
 effect on any given MLIR module. After applying this pass, any given circuit is
 transformed to fulfill the physical constraints imposed by the selected quantum
 device `architecture` and `settings`.
 */
std::unique_ptr<mlir::Pass> createQuakeQMapPass(Architecture &architecture,
                                                const Configuration &settings);

std::unique_ptr<mlir::Pass> createNormalizeArgAnglePass();

// Current count:
// 35 passes
std::unique_ptr<mlir::Pass> createCxRxToRxCxPass();
std::unique_ptr<mlir::Pass> createCxXToXCxPass();
std::unique_ptr<mlir::Pass> createCxZToZCxPass();
std::unique_ptr<mlir::Pass> createRxCxToCxRxPass();
std::unique_ptr<mlir::Pass> createXCxToCxXPass();
std::unique_ptr<mlir::Pass> createZCxToCxZPass();
std::unique_ptr<mlir::Pass> createCxCxCxToSwapPass();
std::unique_ptr<mlir::Pass> createHXHToZPass();
std::unique_ptr<mlir::Pass> createHZHToXPass();
std::unique_ptr<mlir::Pass> createSdgZToSPass();
std::unique_ptr<mlir::Pass> createZSdgToSPass();
std::unique_ptr<mlir::Pass> createSZToSdgPass();
std::unique_ptr<mlir::Pass> createZSToSdgPass();
std::unique_ptr<mlir::Pass> createHCxHToCzPass();
std::unique_ptr<mlir::Pass> createHCzHToCxPass();
std::unique_ptr<mlir::Pass> createHCrxHToCrzPass();
std::unique_ptr<mlir::Pass> createHCrzHToCrxPass();
std::unique_ptr<mlir::Pass> createHRxHToRzPass();
std::unique_ptr<mlir::Pass> createHRzHToRxPass();
std::unique_ptr<mlir::Pass> createSdgSdgSdgToSPass();
std::unique_ptr<mlir::Pass> createSdgSdgToZPass();
std::unique_ptr<mlir::Pass> createSSSToSdgPass();
std::unique_ptr<mlir::Pass> createSSToZPass();
std::unique_ptr<mlir::Pass> createTTToSPass();
std::unique_ptr<mlir::Pass> createRxRxToRxPass();
std::unique_ptr<mlir::Pass> createRyRyToRyPass();
std::unique_ptr<mlir::Pass> createRzRzToRzPass();
std::unique_ptr<mlir::Pass> createHXToZHPass();
std::unique_ptr<mlir::Pass> createHZToXHPass();
std::unique_ptr<mlir::Pass> createXHToHZPass();
std::unique_ptr<mlir::Pass> createZHToHXPass();
std::unique_ptr<mlir::Pass> createHYToYHPass();
std::unique_ptr<mlir::Pass> createYHToHYPass();
std::unique_ptr<mlir::Pass> createXHZToHPass();
std::unique_ptr<mlir::Pass> createZHXToHPass();

} // namespace mqss::opt

// declarative passes
#define GEN_PASS_DECL

#define GEN_PASS_REGISTRATION
#include "Passes/Transforms.h.inc"